// Generated by LiveScript 1.3.1
var fs, jade, path, mkdirRecurse, jadeRecursively;
fs = require('fs');
jade = require('jade');
path = require('path');
mkdirRecurse = function(f){
  var parent;
  if (fs.existsSync(f)) {
    return;
  }
  parent = path.dirname(f);
  if (!fs.existsSync(parent)) {
    mkdirRecurse(parent);
  }
  return fs.mkdirSync(f);
};
jadeRecursively = function(src, des, config, rel){
  var srcFull, desFull, files, i$, len$, file, results$ = [];
  rel == null && (rel = "");
  srcFull = path.join(src, rel);
  desFull = path.join(des, rel);
  files = fs.readdirSync(srcFull).map(function(f){
    return [path.join(srcFull, f), path.join(desFull, f.replace(/\.jade$/, ".html")), path.join(rel, f)];
  });
  for (i$ = 0, len$ = files.length; i$ < len$; ++i$) {
    file = files[i$];
    if (fs.lstatSync(file[0]).isDirectory()) {
      doJade(src, des, config, file[2]);
      continue;
    }
    if (/\.jade$/.exec(file)) {
      mkdirRecurse(path.dirname(file[1]));
      results$.push(fs.writeFileSync(file[1], jade.renderFile(file[0], config)));
    }
  }
  return results$;
};
module.exports = jadeRecursively;